name = "backend"
compatibility_date = "2023-12-01"

[vars]
JWT_SECRET = "asdasdasd"
DATABASE_URL= "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDI4ZTkzMWUtNjliZi00NDcxLWIyNGUtZTQzNDBiZTUzMzYyIiwidGVuYW50X2lkIjoiYmQyYzY5ZjgzZjhlMGI3Y2JkZjgzM2U0OGQzZDRkZDZjZGNjM2M2MjhkOTQxYWVjYzU0ZGNiYzg2MmU2MWMwNCIsImludGVybmFsX3NlY3JldCI6IjM4ZDRjNWRhLTkxMWEtNGU0My1iMDY4LTM4ODNlYmQ5MTFkNSJ9.QPP0MsHotVfSwgsuY7moqE0iuKR-aOo1RiBxNEX8HKA"
